Repository openrewrite/rewrite-spring, pull requests merged in 2023-06, with the labels that each got.

#368 Basic Boot 3.1 Upgrade
  src/main/resources/META-INF/rewrite/spring-boot-31.yml
Labels: recipe, boot-3.0

#372 Upgrade Maven parent only; Gradle should work with BOM already
  src/main/resources/META-INF/rewrite/spring-boot-20.yml
Labels: bug

#370 Set `logging.pattern.level` as part of Sleuth migration
  src/main/java/org/openrewrite/java/spring/cloud2022/AddLoggingPatternLevelForSleuth.java
  src/main/resources/META-INF/rewrite/spring-cloud-2022.yml
  src/test/java/org/openrewrite/java/spring/cloud2022/AddLoggingPatternLevelForSleuthTest.java
  src/test/java/org/openrewrite/java/spring/cloud2022/MigrateCloudSleuthToMicrometerTracingTest.java
  src/test/java/org/openrewrite/java/spring/cloud2022/MigrateProjectTest.java
Labels: boot-3.0

#382 Upgrade Gradle wrapper and Spring Gradle plugins
  build.gradle.kts
  src/main/java/org/openrewrite/gradle/spring/AddSpringDependencyManagementPlugin.java
  src/main/resources/META-INF/rewrite/spring-boot-20.yml
  src/main/resources/META-INF/rewrite/spring-boot-21.yml
  src/main/resources/META-INF/rewrite/spring-boot-22.yml
  src/main/resources/META-INF/rewrite/spring-boot-23.yml
  src/main/resources/META-INF/rewrite/spring-boot-24.yml
  src/main/resources/META-INF/rewrite/spring-boot-25.yml
  src/main/resources/META-INF/rewrite/spring-boot-26.yml
  src/main/resources/META-INF/rewrite/spring-boot-27.yml
  src/main/resources/META-INF/rewrite/spring-boot-30.yml
  src/main/resources/META-INF/rewrite/spring-boot-31.yml
  src/test/java/org/openrewrite/gradle/spring/AddSpringDependencyManagementPluginTest.java
  src/testWithSpringBoot_2_7/java/org/openrewrite/gradle/spring/UpdateGradleTest.java
  src/testWithSpringBoot_2_7/java/org/openrewrite/java/spring/boot2/UpdateMysqlDriverArtifactIdTest.java
Labels: bug
