Repository openrewrite/rewrite-spring, pull requests merged in 2023-03, with the labels that each got.

#304 Removed BeanMethodsNotPublic from SpringBoot2BestPractices
  src/main/resources/META-INF/rewrite/spring-boot-20.yml
Labels: enhancement

#311 Remove calls matching `AuthenticationEntryPointFailureHandler.setRethrowAuthenticationServiceException(true)`
  src/main/java/org/openrewrite/java/spring/security5/UseNewRequestMatchers.java
  src/main/java/org/openrewrite/java/spring/security6/PropagateAuthenticationServiceExceptions.java
  src/main/resources/META-INF/rewrite/spring-security-60.yml
  src/testWithSpringSecurity_5_8/java/org/openrewrite/spring/security6/PropagateAuthenticationServiceExceptionsTest.java
Labels: enhancement, recipe, spring-security

#315 New `UpdatePbkdf2PasswordEncoder` recipe
  build.gradle.kts
  src/main/java/org/openrewrite/java/spring/internal/LocalVariableUtils.java
  src/main/java/org/openrewrite/java/spring/security5/UpdatePbkdf2PasswordEncoder.java
  src/main/java/org/openrewrite/java/spring/security6/PropagateAuthenticationServiceExceptions.java
  src/main/java/org/openrewrite/java/spring/security6/RequireExplicitSavingOfSecurityContextRepository.java
  src/main/java/org/openrewrite/java/spring/security6/UseSha256InRememberMe.java
  src/main/resources/META-INF/rewrite/classpath/spring-security-crypto-5.8.2.jar
  src/test/java/org/openrewrite/java/spring/security5/UpdatePbkdf2PasswordEncoderTest.java
Labels: recipe, spring-security

#319 Fixes #318 Update thymeleaf artifactIds
  src/main/resources/META-INF/rewrite/spring-boot-30.yml
Labels: recipe

#320 Retain versions for thymeleaf-spring5 & thymeleaf-extras-springsecurity5
  src/main/resources/META-INF/rewrite/spring-boot-30.yml
Labels: bug

#322 Tests Boot 3 upgrade recipe descriptor
  src/test/java/org/openrewrite/java/spring/RecipeDescriptorTest.java
Labels: boot-3.0
