Repository openrewrite/rewrite-spring, pull requests merged in 2024-11, with the labels that each got.

#614 Migrate AuditorAware to an Optional<> for spring boot 1 to 2 migration
  build.gradle.kts
  src/main/java/org/openrewrite/java/spring/data/MigrateAuditorAwareToOptional.java
  src/main/java/org/openrewrite/java/spring/util/MemberReferenceToMethodInvocation.java
  src/main/java/org/openrewrite/java/spring/util/concurrent/SuccessFailureCallbackToBiConsumerVisitor.java
  src/main/java/org/openrewrite/java/spring/util/package-info.java
  src/main/resources/META-INF/rewrite/classpath/spring-data-commons-1.13.23.RELEASE.jar
  src/main/resources/META-INF/rewrite/spring-boot-20.yml
  src/test/java/org/openrewrite/java/spring/data/MigrateAuditorAwareToOptionalTest.java
  src/test/java/org/openrewrite/java/spring/util/MemberReferenceToMethodInvocationTest.java
Labels: recipe, boot-2.0

#616 Add new migration case of WebMvcConfigurer
  src/main/java/org/openrewrite/java/spring/framework/MigrateWebMvcConfigurerAdapter.java
  src/testWithSpringBoot_2_1/java/org/openrewrite/java/spring/framework/MigrateWebMvcConfigurerAdapterTest.java
Labels: enhancement

#624 Add `unlessUsing` to `RemoveDependency` to not break compilation
  src/main/resources/META-INF/rewrite/spring-framework-53.yml
Labels: bug, boot-2.4

#626 Drop the old runtime Spring Core dependency brought in through spring-data-mongodb:2.+
  build.gradle.kts
  src/main/java/org/openrewrite/java/spring/data/RefactorSimpleMongoDbFactory.java
  src/main/resources/META-INF/rewrite/classpath/mongo-java-driver-3.12.14.jar
  src/main/resources/META-INF/rewrite/classpath/spring-data-mongodb-2.2.12.RELEASE.jar
  src/main/resources/META-INF/rewrite/spring-data-23.yml
Labels: enhancement

#625 Handle special case of xssProtection
  build.gradle.kts
  src/main/java/org/openrewrite/java/spring/boot2/ConvertToSecurityDslVisitor.java
  src/testWithSpringBoot_2_4/java/org/openrewrite/java/spring/boot2/HeadersConfigurerLambdaDslTest.java
Labels: bug, spring-security

#632 Fix incorrect path computation for Spring API endpoints
  src/main/java/org/openrewrite/java/spring/search/FindApiEndpoints.java
  src/main/java/org/openrewrite/java/spring/trait/SpringRequestMapping.java
  src/testWithSpringBoot_3_0/java/org/openrewrite/java/spring/search/FindApiEndpointsTest.java
Labels: bug

#639 Generate comments for deprecated properties
  src/main/java/org/openrewrite/java/spring/ChangeSpringPropertyValue.java
  src/main/java/org/openrewrite/java/spring/CommentOutSpringPropertyKey.java
  src/main/resources/META-INF/rewrite/spring-boot-20-properties.yml
  src/main/resources/META-INF/rewrite/spring-boot-21-properties.yml
  src/main/resources/META-INF/rewrite/spring-boot-22-properties.yml
  src/main/resources/META-INF/rewrite/spring-boot-23-properties.yml
  src/main/resources/META-INF/rewrite/spring-boot-24-properties.yml
  src/main/resources/META-INF/rewrite/spring-boot-25-properties.yml
  src/main/resources/META-INF/rewrite/spring-boot-26-properties.yml
  src/main/resources/META-INF/rewrite/spring-boot-27-properties.yml
  src/main/resources/META-INF/rewrite/spring-boot-30-properties.yml
  src/main/resources/META-INF/rewrite/spring-boot-31-properties.yml
  src/main/resources/META-INF/rewrite/spring-boot-32-properties.yml
  src/main/resources/META-INF/rewrite/spring-boot-33-properties.yml
  src/main/resources/META-INF/rewrite/spring-boot-34-properties.yml
  src/test/java/org/openrewrite/java/spring/ChangeSpringPropertyValueTest.java
  src/test/java/org/openrewrite/java/spring/CommentOutSpringPropertyKeyTest.java
  src/test/java/org/openrewrite/java/spring/internal/GeneratePropertiesMigratorConfiguration.java
Labels: enhancement, recipe
