Repository openrewrite/rewrite-spring, pull requests merged in 2024-02, with the labels that each got.

#488 Expect new spring property keys to be sorted
  src/test/java/org/openrewrite/java/spring/AddSpringPropertyTest.java
  src/testWithSpringBoot_2_4/java/org/openrewrite/java/spring/boot2/MigrateDatabaseCredentialsTest.java
Labels: bug

#478 Fully remove part provider and last remaining references
  src/main/java/org/openrewrite/java/spring/boot3/AddRouteTrailingSlash.java
  src/main/java/org/openrewrite/java/spring/security5/ReplaceGlobalMethodSecurityWithMethodSecurity.java
  src/testWithSpringBoot_2_7/java/org/openrewrite/java/spring/boot2/AddRouteTrailingSlashTest.java
  src/testWithSpringSecurity_5_7/java/org/openrewrite/spring/security5/ReplaceGlobalMethodSecurityWithMethodSecurityTest.java
Labels: enhancement

#490 Add missing example values
  src/main/java/org/openrewrite/java/spring/ChangeSpringPropertyKey.java
  src/main/java/org/openrewrite/java/spring/ChangeSpringPropertyValue.java
  src/main/java/org/openrewrite/java/spring/RenameBean.java
Labels: documentation

#470 Migrate Swagger to SpringDoc
  build.gradle.kts
  src/main/resources/META-INF/rewrite/springdoc.yml
  src/test/java/org/openrewrite/java/springdoc/SwaggerToSpringDocTest.java
Labels: dependencies, recipe, boot-3.0

#493 Improve `MigrateDefaultHttpClient` documentation
  src/main/java/org/openrewrite/java/apache/httpclient4/MigrateDefaultHttpClient.java
Labels: documentation
