Repository openrewrite/rewrite-spring, pull requests merged in 2024-10, with the labels that each got.

#598 Add recipe to migrate `ResponseStatusException` changes
  src/main/java/org/openrewrite/java/spring/framework/MigrateResponseStatusExceptionGetRawStatusCodeMethod.java
  src/main/resources/META-INF/rewrite/spring-framework-60.yml
  src/test/java/org/openrewrite/java/spring/framework/MigrateResponseStatusExceptionTest.java
Labels: recipe, boot-3.0

#586 Migrate `WebMvcTags` to `ServerRequestObservationConvention`
  build.gradle.kts
  src/main/java/org/openrewrite/java/spring/boot3/MigrateWebMvcTagsToObservationConvention.java
  src/main/resources/META-INF/rewrite/classpath/jakarta.servlet-api-6.1.0.jar
  src/main/resources/META-INF/rewrite/classpath/micrometer-commons-1.11.12.jar
  src/main/resources/META-INF/rewrite/classpath/micrometer-core-1.11.12.jar
  src/main/resources/META-INF/rewrite/classpath/micrometer-observation-1.11.12.jar
  src/main/resources/META-INF/rewrite/spring-boot-30.yml
  src/testWithSpringBoot_3_0/java/org/openrewrite/java/spring/boot3/MigrateWebMvcTagsToObservationConventionTest.java
Labels: enhancement, boot-3.2

#602 Migrate recipe to convert getStatus to getStatusCode with correct types
  src/main/java/org/openrewrite/java/spring/framework/MigrateResponseStatusExceptionGetStatusCodeMethod.java
  src/main/resources/META-INF/rewrite/spring-framework-60.yml
  src/test/java/org/openrewrite/java/spring/framework/MigrateResponseStatusExceptionTest.java
Labels: enhancement, boot-3.0

#603 Include Apache commons-lang3 migration with Spring Boot 2.0 ugprade
  src/main/resources/META-INF/rewrite/spring-boot-20.yml
Labels: recipe, boot-2.0

#604 Include upgrading `jakarta.annotation-api` to 2.1.x
  src/main/resources/META-INF/rewrite/spring-boot-30.yml
Labels: enhancement

#608 SAP cloud logging support migration to SB 3.x
  src/main/resources/META-INF/rewrite/spring-boot-30.yml
Labels: recipe

#612 Replace @Required on setters with @Autowired
  src/main/resources/META-INF/rewrite/spring-framework-51.yml
Labels: recipe
