Repository openrewrite/rewrite-spring, pull requests merged in 2025-06, with the labels that each got.

#721 com.datastax.oss to org.apache.cassandra fix for moving the right set of artifacts with right versions
  src/main/resources/META-INF/rewrite/spring-boot-33.yml
  src/test/java/org/openrewrite/java/spring/kafka/RemoveUsingCompletableFutureTest.java
  src/testWithSpringBoot_3_3/java/org/openrewrite/java/spring/boot3/SpringDataStaxCassandraTest.java
Labels: recipe, boot-3.3

#729 Remove unneeded annotation when migrating from Swagger to SpringDoc
  build.gradle.kts
  src/main/java/org/openrewrite/java/spring/doc/RemoveBeanValidatorPluginsConfiguration.java
  src/main/resources/META-INF/rewrite/springdoc.yml
  src/test/java/org/openrewrite/java/spring/doc/RemoveBeanValidatorPluginsConfigurationTest.java
Labels: recipe, boot-2.6

#727 Migrate Docket to GroupedOpenApi
  .devcontainer/devcontainer.json
  .github/workflows/junie.yml
  build.gradle.kts
  src/main/java/org/openrewrite/java/spring/doc/MigrateDocketBeanToGroupedOpenApiBean.java
  src/main/resources/META-INF/rewrite/classpath.tsv.zip
  src/main/resources/META-INF/rewrite/springdoc.yml
  src/test/java/org/openrewrite/java/spring/doc/MigrateDocketBeanToGroupedOpenApiBeanTest.java
Labels: recipe, boot-2.6

#735 Use springdoc compatibility matrix
  src/main/resources/META-INF/rewrite/spring-boot-31.yml
  src/main/resources/META-INF/rewrite/spring-boot-32.yml
  src/main/resources/META-INF/rewrite/spring-boot-33.yml
  src/main/resources/META-INF/rewrite/spring-boot-34.yml
  src/main/resources/META-INF/rewrite/springdoc.yml
Labels: bug, boot-3.0, boot-3.2, boot-3.3, boot-3.1, boot-3.4

#746 Shorten MaintainTrailingSlashURLMappings code by using an inline visitor
  src/main/java/org/openrewrite/java/spring/boot3/MaintainTrailingSlashURLMappings.java
  src/testWithSpringBoot_2_7/java/org/openrewrite/java/spring/boot2/MaintainTrailingSlashURLMappingsTest.java
Labels: recipe
